#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Temporarily disabled for commit
# npx --no -- commitlint --edit $1
echo "Commitlint temporarily disabled - please use conventional commit format"
