#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Temporarily disabled for commit
# npx lint-staged
echo "Lint-staged temporarily disabled - please run 'npm run lint:fix' manually when possible"
